application:
  appId: STAR-123
  assetId: STAR-123
  sdlcType: EDM
  appName: maven-simple
  appType: WebApplication
  webservice: false
  restApi: false
  microservice: false
  frameworks: 
   - Java
  projectLanguage: Java
  buildSystem: Java
  riskMatrixRevision: Rev1.0
  sourceFilePattern: ".*\\+\\+\\+.*(\\.java|\\.jsp)+.*"
  sensitivePackagePattern: ".*(\\+\\+\\+.*(org\\/hdivsamples\\/security)).*"
  fileChangeThreshold: 20
  
environment:
  scm: "github"
  scmOwner: "evansa"
  scmRepositoryName: "maven-simple"
  scmBranchName: master
  testDeploymentRoot: "vuLnDAP"
  defaultAppPortNumber: "8080"
  imChannelIdentifier: "#bd-alert"
  jiraProjectName: "STAR"
  jiraIssuesQuery: "resolution = \"Unresolved\" AND labels in (Security, Defect)"
